apiVersion: v1
kind: Secret
metadata:
  name: taskflow-secret
type: Opaque
stringData:
  MONGO_USERNAME: "taskflow_admin"
  MONGO_PASSWORD: "CAMBIAR_ESTA_PASSWORD"
  JWT_SECRET: "CAMBIAR_ESTE_JWT_SECRET"
